### ISSUE TITLE
Feature request: More Vec methods

### ISSUE THREAD

**Issue by niklasf** [slightlyoutofphase/staticvec#1]
A couple more methods from [`Vec`](https://doc.rust-lang.org/std/vec/struct.Vec.html) would be useful. In particular:

* [x] [`swap_remove()`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.swap_remove)
* [x] [`retain()`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.retain)
* [x] [`truncate()`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.truncate)

---

* [x] [`impl Extend`](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-Extend%3CT%3E)

**Comment by slightlyoutofphase** [comment]
I definitely want to add more stuff, yeah. Will take a look at these ones first.

**Comment by slightlyoutofphase** [comment]
Just pushed a commit that finishes off the list. Thanks for the request, these were definitely things I'd have needed to add at some point one way or another! Let me know if you think of anything else in the future.

**Comment by niklasf** [comment]
Awesome! Thank you very much.
