### ISSUE TITLE
Write::write_all is incorrect

### ISSUE THREAD

**Issue by Lucretiel** [slightlyoutofphase/staticvec#12]
https://github.com/slightlyoutofphase/staticvec/blob/cbb923416bcdc9404188aef8df54dd32288d75f7/src/trait_impls.rs#L527

write_all needs to guarantee that all of the input bytes were written to the underlying writer. If the StaticVec doesn't have enough capacity, it only writes the beginning of the slice, but still reports success.

**Comment by slightlyoutofphase** [comment]
Shoot, you're right. Will fix!

**Comment by slightlyoutofphase** [comment]
All fixed, with a test added to the suite (which was supposed to already exist, but didn't!)
