### ISSUE TITLE
Add specialized `T: Copy` implementation of `Clone`

### ISSUE THREAD

**Issue by Lucretiel** [slightlyoutofphase/staticvec#16]
Once trait specialization (https://github.com/rust-lang/rust/issues/31844) is stabilized, create a `T: Copy` specialization of `Clone`, which simply copies the slice without relying on the optimizer to notice that it can be done that way. This will allow us to replace a number of "manual copies" with calls to `self.clone()`.

Example of manual copy: https://github.com/slightlyoutofphase/staticvec/blob/da979055ed7d21d4aff76ff5734a03b368ce119e/src/lib.rs#L508-L519

**Comment by slightlyoutofphase** [comment]
Good idea. I've been messing around with specialization a bunch already actually, though I've not committed anything that uses it yet. `Vec` uses it internally for some things already though, for example, and has for quite a while.

Not sure we need to necessarily wait for anything in particular either, as adding another unstable feature flag to the long list of them this crate already uses is fine with me. I'll think about what the best way to go about this might be.

**Comment by Lucretiel** [comment]
It's worth noting that a lot of the discussion in the thread is about soundness holes and potential behavior changes, so even by this library's standards of using unstable features, it may not be ready for an implementation yet.

**Comment by slightlyoutofphase** [comment]
I added this today BTW. Seems to work totally fine. Was really simple so I figured I'd go for it.
