### ISSUE TITLE
`transmute_copy` possibly innefficient

### ISSUE THREAD

**Issue by Lucretiel** [slightlyoutofphase/staticvec#21]
https://github.com/slightlyoutofphase/staticvec/blob/62fc3d031787154f91cc2a1930801159b19a49cc/src/trait_impls.rs#L88

Are there any concerns about the specialized `Clone` impl being inefficient for large `StaticVec`s with small lengths? For instance:

```
let buffer: StaticVec<u8, 4096> = (0..10).collect();

// This will copy 4096 bytes instead of 10 
let buffer2 = buffer.clone();
```

**Comment by slightlyoutofphase** [comment]
It's probably worth doing more in-depth analysis, but generally it seems to be implemented with compiler magic in a way that `copy_to_nonoverlapping` is not and capable of optimizing a lot more granularly / doing the least amount of work it can.

Keep in mind though that at the end of the day StaticVec's array is always the same size, and without incredibly good return-value optimization (which Rust doesn't quite have at the moment) you've gotta "move" it out of the function at some point regardless.

Not much of a hassle to switch back to a `copy_to` function if necessary later anyways.

**Comment by slightlyoutofphase** [comment]
After fiddling around with a few things today, I found a way of using `copy_to_nonoverlapping` that the compiler can actually optimize really well, and that does not copy any more data than necessary, so I just switched the implementation to that.
