### ISSUE TITLE
staticsort depends on libstd

### ISSUE THREAD

**Issue by Amanieu** [slightlyoutofphase/staticvec#29]
I can't use this crate with no_std because the `staticsort` crate which is a dependency of `staticvec` depends on `std`.

**Comment by slightlyoutofphase** [comment]
Oh crap! I totally forgot (for `staticsort`, not this crate) that if you don't literally put `#![no_std]` at the top of the `lib.rs`, then you just _automatically_ depend on std. Good thing it's only been a dependency (and existed) for a few days.

I'm unfortunately not somewhere that I can publish a new version of `staticsort` to `crates.io` until later today, but I can update it on github right away at least, if that helps at all.

Thanks so much for letting me know! I'll close this issue later once I do publish the new `crates.io` version.

**Comment by slightlyoutofphase** [comment]
Just fixed the github version of `staticsort`.

**Comment by slightlyoutofphase** [comment]
I've now published `staticsort` version 0.1.4 to crates.io with the needed `#![no_std]` attribute (and yanked versions 0.1.0 to 0.1.3, as they were all broken in that way.)

I also just published `staticvec` 0.6.9, which amongst other additions / improvements now states its `staticsort` dependency as `staticsort = "^0.1.4"`, so it should update past any existing copies of the now-yanked `staticsort` versions automatically.

Thanks again for letting me know about this, really glad I didn't wind up having it out there broken for `no_std` builds for a long time.
