### ISSUE TITLE
Integrate StaticString with serde (and maybe diesel - partially)

### ISSUE THREAD

**Issue by paulocsanz** [slightlyoutofphase/staticvec#32]
Hey, this wasn't really in the scope of the first PR, and I'm not that motivated to refactor to use const generics, although it's probably an easy change. I may actually do it if I want to procrastinate from other stuff, but I can't promise it.

I've already implemented integration for ArrayString (the basis of the current StaticString) with serde and partially with diesel. I don't remember how well the diesel one works, but it's actually tested so it may be interesting to re-use it, or just ignore for now (diesel kinda sucks to integrate with, most stuff needed are private and they are unwilling to stabilize it in a public API, so some things can't be done with StaticString, but some may be).

You can see the original implementation here: https://github.com/paulocsanz/arraystring/blob/master/src/integration.rs it there is any interest

**Comment by slightlyoutofphase** [comment]
I'll take a look at it, thanks!

**Comment by slightlyoutofphase** [comment]
I just added the Serde functionality to `StaticString` (basically directly adapted from what you had in the linked file), and also expanded the existing `serde_support_demo` to show it off a bit.

I'm gonna pass on the Diesel stuff though, as it just kind of seems like an overly heavy / niche thing to add (and I'm also not really enough of a database programming guy to be particularly enthusiastic about maintaining it.)

Thanks again for the suggestions!
