### ISSUE TITLE
`MaybeUninit::read` has been renamed into `assume_init_read`

### ISSUE THREAD

**Issue by timothee-haudebourg** [slightlyoutofphase/staticvec#42]
Hi,

yesterday the `MaybeUninit::read` function has been renamed into `assume_init_read` via [this commit](https://github.com/rust-lang/rust/pull/76484/commits/a14efd1d0a2f0fa112e4359b9db1e9857589c796). It has been briefly discussed [here](https://github.com/rust-lang/rust/issues/63567#issuecomment-521357943) before that. Of course this means that `staticvec` does not compile with the lastest nightly build.

```
    --> src/lib.rs:1693:29
     |
1693 |       unsafe { Ok(self.data.read()) }
     |                             ^^^^ method not found in `MaybeUninit<[T; N]>`
```

**Comment by slightlyoutofphase** [comment]
I've fixed this issue myself now, as it was the first thing I noticed when I tried to compile the crate earlier today with the latest nightly. Thanks for being proactive though!
