### ISSUE TITLE
Miri flag passing changed

### ISSUE THREAD

**Issue by RalfJung** [slightlyoutofphase/staticvec#44]
`cargo miri test` changed to be more compatible with `cargo test`, but this means we had to find a different way to pass flags to the interpreter, so there now is a `MIRIFLAGS` environment variable for that. The old way still works for now, but is deprecated.

This affects the following line:
https://github.com/slightlyoutofphase/staticvec/blob/32eb423b940ab182f917f7966b09763e9b701c14/ci/run_miri.sh#L11
That should now be `MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test --features="std"`. `cargo miri setup` is also not needed any more.

**Comment by slightlyoutofphase** [comment]
Just edited the script. Thanks for letting me know!
