### ISSUE TITLE
`const trait implementations may not use non-const default functions`

### ISSUE THREAD

**Issue by timothee-haudebourg** [slightlyoutofphase/staticvec#49]
I get a lot of those errors with the latest nightly build.

**Comment by slightlyoutofphase** [comment]
See my comment in your issue about `const_raw_ptr_to_usize_cast`.

**Comment by slightlyoutofphase** [comment]
Does this still occur with the repo as it is now (in your own code, I'm assuming)?

**Comment by slightlyoutofphase** [comment]
This is definitely solved here in the master repo now, and will be solved in the crates.io upload I'll probably do later today also, so I think this issue can be closed.
