### ISSUE TITLE
How unstable is this library?

### ISSUE THREAD

**Issue by timothee-haudebourg** [slightlyoutofphase/staticvec#50]
I see this library is using many unstable features. I'm wondering how much these features are actually required considering that the similar crate `smallvec` is providing a superset of `staticvec` but without using unstable features.

**Comment by slightlyoutofphase** [comment]
Every single one was required at the time of being added for one reason or another. The purpose of this crate was _always_ to push the limits of Rust's const generics functionality as much as was possible at any given time (in a thoroughly well-tested manner). As far as `smallvec`, it's a crate that pre-dates the existence of const generics in Rust entirely, and last time I checked had only introduced them under a feature flag while still by default implementing everything with the classic "array type as generic parameter" syntax (like `SmallVec::<[u8; 4]>::new();` for example).

Going to update my rust installation to the latest nightly ASAP and dig into what needs to be updated to get this compiling again, in any case.

**Comment by slightlyoutofphase** [comment]
Ok, in theory, the GitHub repo here now works exactly as it did before in every way apart from `quicksorted_unstable` no longer being `const`. I'm still not 100% sure this is an unsolvable problem, so I won't push anything "official" to crates.io until I've arrived at what I think is the actual best current solution for everything in nightly rust.

**Comment by slightlyoutofphase** [comment]
Going to close this now due to a planned fixed release releasing relatively shortly.
