### ISSUE TITLE
Use Infallible for from_str

### ISSUE THREAD

**Issue by stevefan1999-personal** [slightlyoutofphase/staticvec#55]
I found an obscure bug:
https://github.com/slightlyoutofphase/staticvec/blob/90f4d79b8d1cb6d8f5055f49c41a591755f75dc8/src/string/string_trait_impls.rs#L214

But according to Rust internal:
https://doc.rust-lang.org/src/alloc/string.rs.html#2351-2357

This should be `Infallible`. One of the implication for this is that I can use `map_err` with `write!` again.

**Comment by slightlyoutofphase** [comment]
Thanks for pointing this out, I switched it when I was doing everything else earlier.
