### ISSUE TITLE
Support for CI

### ISSUE THREAD

**Issue by c410-f3r** [slightlyoutofphase/staticvec#7]
Build is currently broken on `master` and there should be a CI script to at least inform users which commit is green.

**Comment by slightlyoutofphase** [comment]
> Build is currently broken on `master` and there should be a CI script to at least inform users which commit is green.

What error are you getting? It's not broken here.

**Edit:** Oh, shoot, I forgot to *push* the commit that added the `trusted_len` feature flag. I made the commit, published 0.3.3 to crates.io, but then forgot to do a push to github. Fixed now!
